version: '3'


services:
  django:
    image: asia.gcr.io/plant-robot/plant-robot-web:master
    restart: always
    networks:
      - web
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STATIC_URL=${STATIC_URL}
      - GCP=True
      - GS_BUCKET_NAME=${GS_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    volumes:
      - ./key.json:/app/key.json
  caddy:
    image: abiosoft/caddy
    restart: always
    networks:
      - web
    volumes:
      - ./deploy/Caddyfile:/etc/Caddyfile:ro
    ports:
      - 80:80
      - 443:443

networks:
  web:
    external: true
